export const CART_ADD = "ADD_TO_CART";
export const CART_ADD_SUCCESS = "CART_ADD_SUCCESS";
export const CART_ADD_FAILURE = "CART_ADD_FAILURE";
export const CART_ClEAR_ALL = "ClEAR_CART_SUCCESS";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_UPDATE_QUANTITY = "UPDATE_QUANTITY";
